# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-09 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('stars', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('store_owner', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('established_on', models.DateTimeField(blank=True, null=True)),
                ('gst_in', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Store'),
        ),
        migrations.AddField(
            model_name='inventories',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Store'),
        ),
    ]
