# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-09 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review',
            new_name='reviews',
        ),
    ]
