# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-09 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180909_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviews',
            new_name='review',
        ),
    ]
