# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-09 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180909_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='inventories',
            old_name='entity_id',
            new_name='inventory_id',
        ),
    ]
