# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180909_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='entity_id',
            field=models.ForeignKey(default='11', on_delete=django.db.models.deletion.CASCADE, to='myapp.Entities'),
            preserve_default=False,
        ),
    ]
