# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_inventories_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='price',
            field=models.FloatField(),
        ),
    ]
