# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('infra_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('deptt', models.CharField(max_length=256)),
                ('infra_type', models.CharField(max_length=64)),
                ('brand', models.CharField(max_length=264)),
                ('SKU_id', models.CharField(max_length=264)),
                ('licence_id', models.CharField(max_length=264)),
                ('model_id', models.CharField(max_length=264)),
                ('procurement_cost', models.FloatField()),
                ('maintanence_cost', models.FloatField()),
                ('running_cost', models.FloatField()),
                ('procurement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_upgraded_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
