# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='last_upgraded_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='licence_id',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='maintanence_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='model_id',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='procurement_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='running_cost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
