# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth_data', '0002_auto_20180913_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='last_upgraded_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='maintanence_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='procurement_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='running_cost',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
