# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth_data', '0003_auto_20180913_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='last_upgraded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
