# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('networth_data', '0004_auto_20180913_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptt_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='deptt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networth_data.Department'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='infra_type',
            field=models.CharField(choices=[('HW', 'HARDWARE'), ('SW', 'SOFTWARE'), ('LG', 'LOGISTICS')], max_length=64),
        ),
    ]
